#
#

NOM=libmlx.a
SRC= mlx_shaders.c mlx_new_window.m mlx_init_loop.m mlx_new_image.m mlx_xpm.c mlx_int_str_to_wordtab.c
SRC+= mlx_png.c mlx_mouse.m
OBJ1=$(SRC:.c=.o)
OBJ=$(OBJ1:.m=.o)
CFLAGS+=-O2

# add to match string put with X11 in size and position
CFLAGS+= -DSTRINGPUTX11

all: $(NOM)

$(NOM):	$(OBJ)
	@ar -r $(NOM) $(OBJ) > /dev/null
	@ranlib $(NOM) > /dev/null

clean:
	@rm -f $(NOM) $(OBJ) *~ > /dev/null
	@rm -f mlx_app > /dev/null

re: clean all
%.o: %.c
	@cc $(CFLAGS) -c -o $@ $< > /dev/null

%.o: %.m
	@cc $(CFLAGS) -c -o $@ $< > /dev/null

